Repository widdowquinn/pyani, pull requests merged in 2020-07, with the labels that each got.

#198 add --citation argument to common pyani argparser
  pyani/scripts/parsers/common_parser.py
  pyani/scripts/pyani_script.py
Labels: documentation

#201 Issue 199 refactor
  Makefile
  pyani/download.py
  pyani/pyani_tools.py
  pyani/scripts/__init__.py
  pyani/scripts/parsers/download_parser.py
  pyani/scripts/subcommands/subcmd_download.py
  pyani/scripts/tools.py
  tests/conftest.py
  tests/test_legacy_scripts.py
Labels: enhancement

#204 Fixes #203 - ANIm delta parsing gives wrong alignment length
  .gitignore
  CHANGES.md
  CONTRIBUTORS.md
  pyani/anim.py
  tests/fixtures/anim/dataframes/deltadir_result.csv
  tests/test_anim.py
  tests/test_parsing.py
Labels: bug

#203 Update anim.py
  pyani/anim.py
Labels: bug
