Repository widdowquinn/pyani, pull requests merged in 2021-06, with the labels that each got.

#271 Issue 270
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: bug

#273 add new citations for April/May 2021
  docs/citations.rst
Labels: documentation

#282 update CircleCI config (add py39, update images)
  .circleci/config.yml
Labels: tests

#278 Fixes issue 222: Added note relating to use of `pyani plot` with large numbers of genomes
  README.md
Labels: documentation, enhancement

#277 Fixes issue 70: Notify user when ftp download fails because the file has been replaced
  pyani/scripts/genbank_get_genomes_by_taxon.py
Labels: enhancement

#275 Fixes issue 211: Retain original extensions in `.md5` files
  pyani/pyani_files.py
  pyani/scripts/subcommands/subcmd_index.py
  tests/test_input/subcmd_index/nonexistent_hash.txt
  tests/test_subcmd_02_index.py
  tests/test_targets/subcmd_index/GCF_000011745.1_ASM1174v1_genomic.fna.md5
  tests/test_targets/subcmd_index/GCF_000043285.1_ASM4328v1_genomic.fna.md5
  tests/test_targets/subcmd_index/GCF_000185985.2_ASM18598v2_genomic.fna.md5
  tests/test_targets/subcmd_index/GCF_000331065.1_ASM33106v1_genomic.fna.md5
  tests/test_targets/subcmd_index/GCF_000973505.1_ASM97350v1_genomic.fna.md5
  tests/test_targets/subcmd_index/GCF_000973545.1_ASM97354v1_genomic.fna.md5
Labels: documentation, enhancement, interface

#266 Fixes issue 262: Streamline behaviour of `--version` and `--citation` flags
  pyani/scripts/parsers/__init__.py
  pyani/scripts/parsers/anib_parser.py
  pyani/scripts/parsers/anim_parser.py
  pyani/scripts/parsers/common_parser.py
  pyani/scripts/pyani_script.py
Labels: enhancement, interface

#217 Fix anim recovery mode
  pyani/anim.py
  pyani/pyani_files.py
  pyani/pyani_orm.py
  pyani/scripts/subcommands/subcmd_anib.py
  pyani/scripts/subcommands/subcmd_anim.py
  pyani/scripts/subcommands/subcmd_plot.py
Labels: bug

#295 fix #294 - errors due to merging of #217
  pyani/anim.py
  tests/test_anim.py
Labels: bug, tests

#279 Fixes issue 179: Add notes on SGE usage to `README.md`
  README.md
  docs/index.rst
  docs/scheduler.rst
  docs/using_a_scheduler.rst
Labels: documentation, enhancement
