Repository widdowquinn/pyani, pull requests merged in 2021-11, with the labels that each got.

#305 Issue 48: Describe `pyani plot` graphical output.
  docs/basic_use.rst
  docs/images/distribution_identity_run3.png
  docs/images/scatterplot.png
  docs/interpreting_plots.rst
Labels: documentation, visualisation, PR of Supreme Importance

#351 Restore nested anim folders to avoid N^2 files per directory
  pyani/anim.py
  tests/fixtures/anim/deltadir/NC_002696/NC_002696_vs_NC_010338.delta
  tests/fixtures/anim/deltadir/NC_002696/NC_002696_vs_NC_010338.filter
  tests/fixtures/anim/deltadir/NC_002696/NC_002696_vs_NC_011916.delta
  tests/fixtures/anim/deltadir/NC_002696/NC_002696_vs_NC_011916.filter
  tests/fixtures/anim/deltadir/NC_002696/NC_002696_vs_NC_014100.delta
  tests/fixtures/anim/deltadir/NC_002696/NC_002696_vs_NC_014100.filter
  tests/fixtures/anim/deltadir/NC_010338/NC_010338_vs_NC_011916.delta
  tests/fixtures/anim/deltadir/NC_010338/NC_010338_vs_NC_011916.filter
  tests/fixtures/anim/deltadir/NC_010338/NC_010338_vs_NC_014100.delta
  tests/fixtures/anim/deltadir/NC_010338/NC_010338_vs_NC_014100.filter
  tests/fixtures/anim/deltadir/NC_011916/NC_011916_vs_NC_014100.delta
  tests/fixtures/anim/deltadir/NC_011916/NC_011916_vs_NC_014100.filter
  tests/test_ani_data/NC_002696/NC_002696_vs_NC_011916.delta
  tests/test_anim.py
Labels: enhancement

#346 Issue 292: Parallelise plot creation using `multiprocessing`
  pyani/scripts/parsers/plot_parser.py
  pyani/scripts/subcommands/subcmd_plot.py
  requirements.txt
  tests/test_subcmd_06_plot.py
Labels: performance, visualisation

#355 Sort genomes (for stable anim recovery mode)
  pyani/anim.py
  pyani/pyani_files.py
  pyani/scripts/subcommands/subcmd_anim.py
  tests/conftest.py
  tests/test_anim.py
Labels: bug, performance
